/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface cacheEntity {
  'expiration': number;
  'key': string;
  'value': string;
}
export interface cache_locksEntity {
  'expiration': number;
  'key': string;
  'owner': string;
}
export interface clientsEntity {
  'address': string;
  'company_name': string;
  'contact_person': string;
  'created_at'?: Date | null;
  'email': string;
  'id'?: string;
  'organization_id': string;
  'phone': string;
  'updated_at'?: Date | null;
}
export interface failed_jobsEntity {
  'connection': string;
  'exception': string;
  'failed_at'?: Date;
  'id'?: string;
  'payload': string;
  'queue': string;
  'uuid': string;
}
export interface invitationsEntity {
  'created_at'?: Date | null;
  'email': string;
  'expires_at': Date;
  'id'?: string;
  'inviter_id': string;
  'organization_id': string;
  'token': string;
  'updated_at'?: Date | null;
}
export interface invoicesEntity {
  'amount': number;
  'client_id': string;
  'created_at'?: Date | null;
  'id'?: string;
  'invoice_number': string;
  'organization_id': string;
  'project_id': string;
  'status': any;
  'updated_at'?: Date | null;
}
export interface job_batchesEntity {
  'cancelled_at'?: number | null;
  'created_at': number;
  'failed_job_ids': string;
  'failed_jobs': number;
  'finished_at'?: number | null;
  'id': string;
  'name': string;
  'options'?: string | null;
  'pending_jobs': number;
  'total_jobs': number;
}
export interface jobsEntity {
  'attempts': number;
  'available_at': number;
  'created_at': number;
  'id'?: string;
  'payload': string;
  'queue': string;
  'reserved_at'?: number | null;
}
export interface migrationsEntity {
  'batch': number;
  'id'?: number;
  'migration': string;
}
export interface model_has_permissionsEntity {
  'model_id': string;
  'model_type': string;
  'permission_id': string;
}
export interface model_has_rolesEntity {
  'model_id': string;
  'model_type': string;
  'role_id': string;
}
export interface organizationsEntity {
  'created_at'?: Date | null;
  'id'?: string;
  'name': string;
  'updated_at'?: Date | null;
}
export interface p_c_a_reportsEntity {
  'address': string;
  'basement': any;
  'building': string;
  'client_id': string;
  'created_at'?: Date | null;
  'fondation': string;
  'id'?: string;
  'name': string;
  'non_residential_units'?: number;
  'numbers_of_floors': number;
  
  /* Percentage of total lot area */
  'occupation_of_the_building': number;
  'occupation_of_the_property': string;
  'organization_id': string;
  'project_id': string;
  'residential_units': number;
  'structure': string;
  
  /* Measured in square meters */
  'surface_area_of_the_building': number;
  
  /* Measured in square meters */
  'total_site_area': number;
  'updated_at'?: Date | null;
  'year_of_construction': number;
}
export interface password_reset_tokensEntity {
  'created_at'?: Date | null;
  'email': string;
  'token': string;
}
export interface permissionsEntity {
  'created_at'?: Date | null;
  'guard_name': string;
  'id'?: string;
  'name': string;
  'updated_at'?: Date | null;
}
export interface project_userEntity {
  'created_at'?: Date | null;
  'project_id': string;
  'updated_at'?: Date | null;
  'user_id': string;
}
export interface projectsEntity {
  'address': string;
  'budget': number;
  'client_id': string;
  'created_at'?: Date | null;
  'currency'?: string | null;
  'deadline': Date;
  'department': string;
  'id'?: string;
  'language': 'english' | 'french';
  'manager': string;
  'opening_date': Date;
  'organization_id': string;
  'sales_representative_name': string;
  'status': 'ongoing' | 'completed' | 'canceled';
  'type': string;
  'updated_at'?: Date | null;
}
export interface quotesEntity {
  'budget': number;
  'client_id': string;
  'created_at'?: Date | null;
  'id'?: string;
  'organization_id': string;
  'project_address': string;
  'project_id': string;
  'project_type': string;
  'quote_language': 'english' | 'french';
  'quote_status': 'in_preparation' | 'sent' | 'approved' | 'rejected';
  'sales_representative_name': string;
  'updated_at'?: Date | null;
}
export interface role_has_permissionsEntity {
  'permission_id': string;
  'role_id': string;
}
export interface rolesEntity {
  'created_at'?: Date | null;
  'guard_name': string;
  'id'?: string;
  'name': string;
  'updated_at'?: Date | null;
}
export interface sessionsEntity {
  'id': string;
  'ip_address'?: string | null;
  'last_activity': number;
  'payload': string;
  'user_agent'?: string | null;
  'user_id'?: string | null;
}
export interface time_sheetsEntity {
  'created_at'?: Date | null;
  'details'?: string | null;
  'id'?: string;
  'organization_id': string;
  'project_id': string;
  'task_performed': 'visit' | 'research' | 'fieldwork' | 'report';
  'updated_at'?: Date | null;
  'user_id': string;
  'worked_duration': number;
}
export interface usersEntity {
  'created_at'?: Date | null;
  'email': string;
  'email_verified_at'?: Date | null;
  'id'?: string;
  'name': string;
  'organization_id'?: string | null;
  'password': string;
  'remember_token'?: string | null;
  'updated_at'?: Date | null;
}
export interface workloadsEntity {
  'created_at'?: Date | null;
  'deadlines': Object;
  'id'?: string;
  'updated_at'?: Date | null;
  'user_id': string;
}
