/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface cacheEntity {
  'expiration': number;
  'key': string;
  'value': string;
}
export interface cache_locksEntity {
  'expiration': number;
  'key': string;
  'owner': string;
}
export interface clientsEntity {
  'address': Object;
  'company_name': string;
  'contact_person': string;
  'created_at'?: Date | null;
  'email': string;
  'id'?: string;
  'organization_id': string;
  'phone'?: string | null;
  'updated_at'?: Date | null;
}
export interface failed_jobsEntity {
  'connection': string;
  'exception': string;
  'failed_at'?: Date;
  'id'?: string;
  'payload': string;
  'queue': string;
  'uuid': string;
}
export interface filesEntity {
  'created_at'?: Date | null;
  'id': string;
  'mime_type': string;
  'name': string;
  'parent_id': string;
  'path': string;
  'size': string;
  'updated_at'?: Date | null;
}
export interface invitationsEntity {
  'created_at'?: Date | null;
  'email': string;
  'expires_at': Date;
  'id'?: string;
  'inviter_id': string;
  'organization_id': string;
  'token': string;
  'updated_at'?: Date | null;
}
export interface invoice_itemsEntity {
  'created_at'?: Date | null;
  'currency'?: string | null;
  'description'?: string | null;
  'discount_percentage'?: number | null;
  'id'?: string;
  'invoice_id': string;
  'label'?: string | null;
  'metadata'?: Object | null;
  'quantity'?: number;
  'quantity_unit'?: string | null;
  'tax_percentage'?: number | null;
  'unit_discount'?: string | null;
  'unit_price'?: string | null;
  'unit_tax'?: string | null;
  'updated_at'?: Date | null;
}
export interface invoicesEntity {
  'buyer_id'?: string | null;
  'buyer_information'?: Object | null;
  'buyer_type'?: string | null;
  'client_id'?: string;
  'created_at'?: Date | null;
  'currency'?: string | null;
  'description'?: string | null;
  'discount_amount'?: string | null;
  'discounts'?: Object | null;
  'due_at'?: Date | null;
  'id'?: string;
  'invoiceable_id'?: string | null;
  'invoiceable_type'?: string | null;
  'logo'?: any | null;
  'metadata'?: Object | null;
  'parent_id'?: string | null;
  'project_id'?: string;
  'seller_id'?: string | null;
  'seller_information'?: Object | null;
  'seller_type'?: string | null;
  'serial_number': string;
  'serial_number_count': string;
  'serial_number_format': string;
  'serial_number_month'?: number | null;
  'serial_number_prefix'?: string | null;
  'serial_number_serie'?: string | null;
  'serial_number_year'?: number | null;
  'state': string;
  'state_set_at'?: Date | null;
  'subtotal_amount'?: string | null;
  'tax_amount'?: string | null;
  'tax_exempt'?: string | null;
  'tax_type'?: string | null;
  'total_amount'?: string | null;
  'type'?: string;
  'updated_at'?: Date | null;
}
export interface job_batchesEntity {
  'cancelled_at'?: number | null;
  'created_at': number;
  'failed_job_ids': string;
  'failed_jobs': number;
  'finished_at'?: number | null;
  'id': string;
  'name': string;
  'options'?: string | null;
  'pending_jobs': number;
  'total_jobs': number;
}
export interface jobsEntity {
  'attempts': number;
  'available_at': number;
  'created_at': number;
  'id'?: string;
  'payload': string;
  'queue': string;
  'reserved_at'?: number | null;
}
export interface migrationsEntity {
  'batch': number;
  'id'?: number;
  'migration': string;
}
export interface model_has_permissionsEntity {
  'model_id': string;
  'model_type': string;
  'permission_id': string;
}
export interface model_has_rolesEntity {
  'model_id': string;
  'model_type': string;
  'role_id': string;
}
export interface organizationsEntity {
  'address'?: Object | null;
  'brand_color'?: string | null;
  'created_at'?: Date | null;
  'email': string;
  'id'?: string;
  'logo'?: string | null;
  'name': string;
  'phone_number'?: string | null;
  'updated_at'?: Date | null;
}
export interface p_c_a_reportsEntity {
  'address': string;
  'basement': any;
  'building': string;
  'client_id': string;
  'created_at'?: Date | null;
  'fondation': string;
  'id'?: string;
  'name': string;
  'non_residential_units'?: number;
  'numbers_of_floors': number;
  
  /* Percentage of total lot area */
  'occupation_of_the_building': number;
  'occupation_of_the_property': string;
  'organization_id': string;
  'project_id': string;
  'residential_units': number;
  'structure': string;
  
  /* Measured in square meters */
  'surface_area_of_the_building': number;
  
  /* Measured in square meters */
  'total_site_area': number;
  'updated_at'?: Date | null;
  'year_of_construction': number;
}
export interface password_reset_tokensEntity {
  'created_at'?: Date | null;
  'email': string;
  'token': string;
}
export interface permissionsEntity {
  'created_at'?: Date | null;
  'guard_name': string;
  'id'?: string;
  'name': string;
  'updated_at'?: Date | null;
}
export interface project_pipeline_stagesEntity {
  'completed_at'?: Date | null;
  'created_at'?: Date | null;
  'id'?: string;
  'is_system_default'?: any;
  'name': string;
  'notes'?: string | null;
  'project_id'?: string | null;
  'stage_order'?: number;
  'status'?: string;
  'updated_at'?: Date | null;
}
export interface project_userEntity {
  'created_at'?: Date | null;
  'project_id': string;
  'updated_at'?: Date | null;
  'user_id': string;
}
export interface projectsEntity {
  'address'?: string | null;
  'budget'?: number | null;
  'client_id': string;
  'created_at'?: Date | null;
  'currency': string;
  'current_project_pipeline_stage_id'?: string | null;
  'deadline'?: Date | null;
  'department'?: string | null;
  'id'?: string;
  'language': 'english' | 'french';
  'manager': string;
  'notes'?: string | null;
  'opening_date'?: Date | null;
  'organization_id': string;
  'sales_representative_name'?: string | null;
  'status': 'ongoing' | 'completed' | 'canceled';
  'type': string;
  'updated_at'?: Date | null;
}
export interface proposalsEntity {
  'accepted_at'?: Date | null;
  'client_id': string;
  'created_at'?: Date | null;
  'currency': string;
  'description'?: string | null;
  'expires_at'?: Date | null;
  'id'?: string;
  'invoice_id'?: string | null;
  'organization_id'?: string | null;
  'project_id'?: string | null;
  'rejected_at'?: Date | null;
  'sent_at'?: Date | null;
  'state'?: 'draft' | 'sent' | 'viewed' | 'accepted' | 'rejected' | 'expired' | 'archived';
  'subtotal_amount'?: number;
  'tax_amount'?: number;
  'title': string;
  'total_amount'?: number;
  'updated_at'?: Date | null;
}
export interface role_has_permissionsEntity {
  'permission_id': string;
  'role_id': string;
}
export interface rolesEntity {
  'created_at'?: Date | null;
  'guard_name': string;
  'id'?: string;
  'name': string;
  'updated_at'?: Date | null;
}
export interface sessionsEntity {
  'id': string;
  'ip_address'?: string | null;
  'last_activity': number;
  'payload': string;
  'user_agent'?: string | null;
  'user_id'?: string | null;
}
export interface time_sheetsEntity {
  'created_at'?: Date | null;
  'details'?: string | null;
  'id'?: string;
  'organization_id': string;
  'project_id': string;
  'project_pipeline_stage_id': string;
  'task_performed': string;
  'updated_at'?: Date | null;
  'user_id': string;
  'worked_duration': number;
}
export interface usersEntity {
  'created_at'?: Date | null;
  'email': string;
  'email_verified_at'?: Date | null;
  'id'?: string;
  'name': string;
  'organization_id'?: string | null;
  'password': string;
  'remember_token'?: string | null;
  'updated_at'?: Date | null;
}
export interface workloadsEntity {
  'created_at'?: Date | null;
  'deadlines': Object;
  'id'?: string;
  'updated_at'?: Date | null;
  'user_id': string;
}
